Use inline script because reusable workflow cannot access its local files

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -43,7 +43,6 @@ on:
 
 env:
   CHECKOUT_PATH: source
-  ASSERT_NOT_EQUALS: ${{ github.workspace }}/scripts/assert_not_equals
 
 jobs:
   debug:
@@ -54,21 +53,35 @@ jobs:
   check:
     if: inputs.push-image
     runs-on: ubuntu-latest
+    env:
+      ASSERT_NOT_EMPTY: |
+        assert_not_empty() {
+          ACTUAL="$1"
+
+          if [ "$ACTUAL" == '' ]; then
+            echo '::error::Not expected empty value'
+            exit 1
+          fi
+          echo "::debug::'$ACTUAL' is not empty"
+        }
+        assert_not_empty
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Check inputs
         env:
           DOCKERHUB_REPOSITORY: ${{ inputs.dockerhub-repository }}
+        shell: sh
         run: |
-          $ASSERT_NOT_EQUALS "" "$DOCKERHUB_REPOSITORY"
+          $ASSERT_NOT_EMPTY "$DOCKERHUB_REPOSITORY"
       - name: Check secrets
         env:
           DOCKERHUB_USERNAME: ${{ secrets.dockerhub-username }}
           DOCKERHUB_TOKEN: ${{ secrets.dockerhub-token }}
+        shell: sh
         run: |
-          $ASSERT_NOT_EQUALS "" "$DOCKERHUB_USERNAME"
-          $ASSERT_NOT_EQUALS "" "$DOCKERHUB_TOKEN"
+          $ASSERT_NOT_EMPTY "$DOCKERHUB_USERNAME"
+          $ASSERT_NOT_EMPTY "$DOCKERHUB_TOKEN"
   build:
     needs: [check]
     runs-on: ubuntu-latest
